[package]
name = "rust-admin-panel"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
actix-web = "4"
env_logger = "0.11.6"
log = "0.4.25"
serde_json = "1.0.138"
tinytemplate = "1.2.1"
