[package]
name = "rust-admin-panel"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
actix-web = "4"
diesel = { version = "2.2.7", features = ["mysql", "r2d2"] }
diesel_migrations = "2.2.0"
dotenv = "0.15.0"
env_logger = "0.11.6"
log = "0.4.25"
r2d2 = "0.8.10"
serde_json = "1.0.138"
serde = { version = "1.0.217", features = ["derive"] }
actix-session = { version = "0.10.1", features = ["redis-session"] }
serde_derive = "1.0.218"
handlebars = "6.3.1"
actix-utils = "3.0.1"
futures-util = "0.3.31"
http = "0.2.12"
flatten_json = "0.1.0"
accept-language = "3.1.0"
argon2 = "0.5.3"
lettre = "0.11.15"
