-- Your SQL goes here
CREATE TABLE users (
   id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
   email VARCHAR(255) NOT NULL UNIQUE,
   password VARCHAR(255) NULL DEFAULT NULL,
   locale VARCHAR(6) NULL DEFAULT NULL,
   surname VARCHAR(255) NULL DEFAULT NULL,
   name VARCHAR(255) NULL DEFAULT NULL,
   patronymic VARCHAR(255) NULL DEFAULT NULL
);

INSERT INTO users (email)
VALUES ('admin@admin.example');